title: "rez.red"
description: "Landing Page"
theme: jekyll-theme-hacker

url: "https://rez.red"   # custom domain at root
baseurl: ""              # empty for root
repository: ejee21/rez.red

plugins:
  - jekyll-redirect-from
github:
  is_project_page: false
