title: "rez.red"
description: "My hacker-themed site"
theme: jekyll-theme-hacker

url: "https://rez.red"   # custom domain at root
baseurl: ""              # empty for root
repository: ejee21/rez.red
